# Site settings
title: Shoshana and Alex's Wedding Website
email: shoshandalexwedding@gmail.com
description: "We're getting married! Alex made a website!"


# Team names, titles and social links
facts:
- title: How We Met
  pic: 1
  text: Alex and Shoshana met in NFTY-MAR, a Jewish youth movement in 2004ish. They kissed once, but lost touch for 10 years.


# Build settings
markdown: kramdown
permalink: pretty
