# Site settings
title: Shoshana and Alex's Wedding Website
email: shoshandalexwedding@gmail.com
description: "We're getting married! Alex made a website!"


# Team names, titles and social links
facts:
- title: How We Met
  pic: nfty_pic
  text: We met sometime around 2004 in regional youth group. Exact dates are fuzzy. We were pretty good instant messenger friends (Winchester and Takoma Park seemed so far apart then!) throughout high school, we lost touch after high school and didn't speak for a decade or so.

- title: How We Re-Met
  pic: jswipe
  text: We reconnected on JSwipe. Alex still thinks asking Shoshana if she wanted to grab some food and they "could decide if it was a date after" was smooth. Shoshana disagrees.

# Build settings
markdown: kramdown
permalink: pretty
