# Site settings
title: Shoshana and Alex's Wedding Website
email: shoshandalexwedding@gmail.com
description: "We're getting married! Alex made a website!"


# Team names, titles and social links
facts:
- title: How We Met
  pic: nfty_pic
  text: We met sometime around 2004 in regional youth group. We were pretty good instant messenger friends (Winchester and Takoma Park seemed so far apart then!) throughout high school, but lost touch and didn't speak for a decade or so.

- title: How We Re-Met
  pic: jswipe
  text: We reconnected on JSwipe. Alex still thinks suggesting that they grab some food and "decide if it was a date after" was smooth. Shoshana disagrees.

- title: First date
  pic: first_date
  text: Our first date was a picnic in one of DC's beautiful parks. It was kinda awkward until the bottle of wine had been finished, Alex shared that he really needed to pee, and Shosh revealed she is a troll and started poking his belly. (Our first pic together!)

- title: Flowers
  pic: flowers
  text: It is impossible to walk around DC neighborhoods without running into beautiful flower gardens, and Shoshana's excitement redefines "stopping to smell the roses". This behavior has increasingly rubbed off on Alex, who occasionally beats Shosh to the punch on flower-spotting these days.

- title: Travel
  pic: travel
  text: We've both traveled separately, and knew finding the perfect travel buddy was important. So far we've been to Austin, Boston, Greece, Israel & Palestine, Ohiopyle PA, Puerto Rico, and the Istanbul Airport together. We can't wait for more.

- title: Proposal
  pic: proposal
  text: After a great deal of foreshadowing, Shoshana came home to a room full of her favorite things (French 75s, Flowers, and Marshmallows) in their apartment. Alex read aloud his journal entry from before their first date about how, "I feel like my life could change in a pretty big way." Obviously his premonitions were right. Shoshana said yes.


# Wedding party: Jeff, Xaq, Bruno, Carter, Louis, Eliot, jswipe, Jenna, John, Rachel, Lizzi, Nicole
wp:

- name: Eliot Gold (Best Man)
  pic: eliot
  text: Eliot has been Alex's favorite (and only) brother since he was born when Alex was 2 1/2. Shoshana is delighted that Eliot will soon be her favorite (and only) brother. Eliot requested that he be allowed to drive the bus at the wedding. A decision is pending.

- name: McKenna Todd (Maid of Honor)
  pic: mckenna
  text: McKenna is Shoshana’s favorite (Alex is a close 2nd). Hailing from Germany, Philly, Springfield, and Phoenix, McKenna is the definition of a self-starter and is always the life of the party. McKenna and Shoshana found each other on the George Mason Off-Campus Housing website… roommates for 3 years and best friends fo’ life. 

- name: Lizzi Albert
  pic: lizzi
  text: Lizzi is an accomplished professional actress and Alex’s non-biological twin sister. She frequently reassured Alex that he’d eventually find someone who was a perfect fit and be able to stop dating. Luckily for Alex, Lizzi was right as usual. Luckily for Lizzi, Alex was right that he’d complain much less when he could stop dating.

- name: Xaq Rothman
  pic: xaq
  text: Xaq is a master of the bass, the internet, and facial hair. He has introduced Alex to many of his favorite bands over the years. When Alex and Xaq met in 7th grade, Xaq was renowned for his impressions of large terrifying lizards including velociraptors and zerglings. Luckily, very little has changed.

- name: Bruno Falcon
  pic: bruno
  text: Bruno is an improv star, video producer, and <a href = https://applyingtoeverything.xyz/>podcast host</a>. Over the years, he and Alex have had many lengthy disagreements about philosophy, most of which conclude when they realize they’re actually arguing the same side.

- name: Carter Baldwin
  pic: carter
  text: Carter and Alex first became friends in kindergarten and often butted heads over the appropriate color for Lego castle walls or just how destructive a single lightsaber stroke should be. Since then, it has become abundantly clear that Alex should defer to Carter on all topics Lego-related. Who’s the bigger Star Wars nerd isn’t always so clear.

- name: Louis Weil
  pic: louis
  text: Louis is a medical professional, dynamite guitarist, and avid collector of puns. Louis and Alex’s friendship started in Carter’s living room in 4th grade and has spanned the time and space since then, including traveling together in Israel and a 3-week trip to Thailand where they were mistaken for a recently married couple in a cooking class.

- name: Nicole Falkenburry
  pic: nicole
  text: Nicole is the little sister Shoshana always wanted and one of the only things Shoshana really liked about sorority life. Nicole and Shoshana first bonded over a hatred of exercise, but have since attended several yoga classes together. Now while both living in the district they hang out all the time, proving that sorority sisters really do become your bridesmaids. Nicole is the most honest and compassionate of friends and Shoshana would be lost without her.

- name: Jeffrey Holliday
  pic: jeffrey
  text: Jeffrey is a reliable source of expertise on bikes, a superb cook of Japanese street food, and a marvelous trivia night curator. Alex and Jeffrey became friends in Ms.Hishikawa’s 3rd grade class and continued their friendship through Alex’s .000 batting seasons on the mighty Kidshop Krushers, summers hiking the Shenandoah mountains, and Alex’s brief foray into Segway tour-guiding (a job Alex got as part of the Jeffrey Holliday friendship nepotism program).

- name: Rachel Ray
  pic: rachel
  text: Rachel and Shoshana first met at a religious school playgroup when they were only months old. Since then, their friendship has survived hot glue guns, bunk-bed ladder slides, basically running the religious school, first boyfriends, college life, and now adultish life. Rachel and Shoshana share a passion for international relations and development and a deep devotion to making the world a better place.

- name: Jenna Koltz
  pic: jenna
  text: Jenna was randomly selected by an old roommate to become McKenna and Shoshana’s roommate in the summer of 2010. Over that summer Jenna and Shoshana bonded during pool visits discussing Alaska and general young heartbreak. Jenna is always the person to call for bug identification and level-headed advice, not to mention the best pedicure partner around. (Sorry, Eliot.)

- name: John Koltz
  pic: john
  text: John was first introduced to Shoshana as the boyfriend in Alaska (see Jenna Koltz). Later they became good friends and John became more than just the best friend’s boyfriend. John, Shoshana, and McKenna have enjoyed many concerts together. Jenna and John were always very gracious and in allowing Shoshana to be their perpetual third-wheel until Alex made his appearance. Now we have a fifth-wheel, baby Vera!

registry:

- name: REI
  pic: rei
  link: https://www.rei.com/GiftRegistryDetails/15196913

- name: Crate And Barrel
  pic: crate_and_barrel
  link: https://www.crateandbarrel.com/gift-registry/shoshana-abrams-and-alex-gold/r5742432

- name: Zola
  pic: zola
  link: https://www.zola.com/registry/alexandshoshana

# Build settings
markdown: kramdown
permalink: pretty
